name: siliconmetatrader5-kasm

services:
  mt5-kasm:
    build: .
    platform: linux/amd64
    container_name: siliconmetatrader5-kasm
    environment:
      - TZ=Europe/Istanbul
      - TITLE=SiliconMetaTrader5-Kasm
      - START_DOCKER=false
      - NO_FULL=true
      - KCLIENT_AUDIO=0
    ports:
      - 3000:3000
      - 3001:3001
      - 8001:8001
    restart: unless-stopped
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - siliconmetatrader5_kasm_config:/config
      - siliconmetatrader5_kasm_logs:/siliconmt5/logs

volumes:
  siliconmetatrader5_kasm_config:
  siliconmetatrader5_kasm_logs:
