; MetaTrader 5 Configuration File
[Common]
NewsEnable=0
EventsEnable=0
Portable=1

[Charts]
MaxBars=1000000
PrintColor=0

[Expert]
AllowDllImport=1
AllowWebRequest=1
AllowTrailingStop=1
AllowAlgoTrading=1
EnableAlgoTrading=1